name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  my_new_project:
    # This matches your models/staging folder
    staging:
      +schema: staging_dv
      +materialized: view  # Staging is usually a view to save storage

    # This matches your models/vault folder
    dv:     #folder name  created under model
      +schema: dv
      +materialized: table # Vault tables (Hubs/Links/Sats) must be tables

    marts:
      +schema: marts
      +materialized: view

dispatch:
  - macro_namespace: dbt_automatedv
    search_order: ['dbt_automatedv', 'automate_dv']

vars:
  automate_dv:
    hash: 'MD5'          # This is the algorithm
    hash_datatype: 'BINARY' # This ensures the data types match

    